### ISSUE TITLE
Cloudformation Stack Create Fails on BucketTables WebsiteContent

### ISSUE THREAD

**Issue by Greglobrien** [aws-samples/aws-elemental-instant-video-highlights#4]
Hi,
I'll start off with the fact that I could be missing something here, but I thought I should mention in attempting to use the Catfinder5001 I was unable to get the CF to fully deploy.  I tested on twice us-east-1 and us-west-2. It would always fail on the BucketTablesModuleStack during WebsiteContent. 
Error and Json:
[ERROR] 2019-05-26T23:20:24.833Z 01842b47-5a80-4672-bcf6-5d7020d72fec Error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied 

`{ "Status": "FAILED", "StackId": "arn:aws:cloudformation:us-east-1:<AWS ID>:stack/catfinder5001-BucketTablesModuleStack-YOXP40KV3094/b466f540-800c-11e9-a692-0a437bda7b86", "PhysicalResourceId": "b466f540-800c-11e9-a692-0a437bda7b86-WebsiteContent", "Reason": "See the details in CloudWatch Log Stream: 2019/05/26/[$LATEST]b74c480b83dd48679e40ca1c5d7cdccc", "RequestId": "da03d967-ee79-43af-9f05-4be143583d3c", "Data": { "Exception": "An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied" }, "LogicalResourceId": "WebsiteContent" }`

I was able to get around this issue by deleting the (WebsiteContent) copy command from the BucketTables CF and then I simply manually copied in the website files to the demo bucket, so considering I was able to access the rodeolabz bucket I'm not sure why the lambda couldn't get at it.  And it seemed to work after that.

Thanks for the demo!

**Comment by sputtemans** [comment]
Hi,
I also got an error when trying it to deploy. But I'm not that experienced to get around the issue.

@Greglobrien : would it be possible to give more detail how and where you deleted that command?

Thanks for the very nice demo by the way!

Regards

Sven

**Comment by morjoan** [comment]
The resource (bucket) for the read access policy of the Lambda was missing the region portion so it was failing to access the wrong bucket. Fixed now. Please give it another go.

**Comment by sputtemans** [comment]
thanks!
